name = "echomind-api"
main = "src/index.ts"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
# 環境變數通過 Cloudflare Dashboard 或 wrangler secret 設定
# 以下為示例，實際部署時需要替換

# 用於開發環境的一些默認設置
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"

[env.production]
# 生產環境配置
# 這裡的變數值會被 Dashboard 中設置的值覆蓋
name = "echomind-api"
# 添加 vars 部分以解決部署警告
[env.production.vars]
# 提醒：實際的 API 金鑰應通過 wrangler secret 設定
# wrangler secret put GROQ_API_KEY --env production
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"

[env.staging]
# 測試環境配置
name = "echomind-api-staging"
# 添加 vars 部分解決警告
[env.staging.vars]
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"

[env.development]
# 開發環境配置
name = "echomind-api-dev" 