name = "echomind-api"
main = "src/index.ts"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
# 環境變數通過 Cloudflare Dashboard 或 wrangler secret 設定
# 以下為示例，實際部署時需要替換

# 用於開發環境的一些默認設置
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"
# Pinecone 配置
PINECONE_ENVIRONMENT = "asia-southeast1-gcp"
PINECONE_INDEX = "echomind2"

# 備註：敏感資訊如 API 金鑰請使用 wrangler secret 設定，例如：
# wrangler secret put COHERE_API_KEY
# wrangler secret put PINECONE_API_KEY

# 以下環境變數需要在 Cloudflare Dashboard 中進行設置
# - PINECONE_API_KEY
# - PINECONE_INDEX
# - COHERE_API_KEY
# - PYTHON_API_URL (新增) - Python API 服務的基礎 URL

[env.production]
# 生產環境配置
# 這裡的變數值會被 Dashboard 中設置的值覆蓋
name = "echomind-api"
# 添加 vars 部分以解決部署警告
[env.production.vars]
# 提醒：實際的 API 金鑰應通過 wrangler secret 設定
# wrangler secret put GROQ_API_KEY --env production
# wrangler secret put COHERE_API_KEY --env production
# wrangler secret put PINECONE_API_KEY --env production
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"
PINECONE_ENVIRONMENT = "us-east-1"
PINECONE_INDEX = "echomind2"

[env.staging]
# 測試環境配置
name = "echomind-api-staging"
# 添加 vars 部分解決警告
[env.staging.vars]
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"
PINECONE_ENVIRONMENT = "us-east-1"
PINECONE_INDEX = "echomind2"

[env.development]
# 開發環境配置
name = "echomind-api-dev"
[env.development.vars]
R2_ENDPOINT = "example-bucket.your-subdomain.r2.dev"
PINECONE_ENVIRONMENT = "us-east-1"
PINECONE_INDEX = "echomind2" 